### ISSUE TITLE
建议添加模组

### ISSUE THREAD

**Issue by Chococar-NSW** [kuzuanpa/Modpack-TerraFirma-Rescue-Unofficial#2]
**Version of modpack｜整合包版本**

- 4.1.4.1

**Describe your suggestion｜描述你的建议**

为了能够优化效能与便利，建议以下模组(皆来自于GTNH)

1. [Angelica](https://github.com/GTNewHorizons/Angelica)
   GTNH官方制作的Optifine替代品，内含移植高版本钠与其他优化模组
   有前置需求与冲突模组
2. [Findit](https://github.com/GTNewHorizons/Findit)
   同样是GTNH官方制作，用于便利寻找物品(箱子里或方块)
3. [Share-Where-I-am](https://github.com/GTNewHorizons/Share-Where-I-am)
   JourneyMap附加，可以用于多人共享所在位置或导航点
   语言为Kotlin，需额外使用[Forgelin](https://github.com/GTNewHorizons/Forgelin)
4. [ServerUtilities](https://github.com/GTNewHorizons/ServerUtilities)
   FTBUtilities与FTBLib的合并版模组

**Comment by kuzuanpa** [comment]
angelica已计划添加，但是打算等alpha阶段结束之后再添加，目前该mod不很稳定
第二个findit可以添加
第三个用处不大，而且为它引入kotlin支持有些小题大做
第四个不会添加，FTBu是已被移除的mod,大部分功能已使用其他mod代替
